<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Sts2Packmaster.VanillaPacks</RootNamespace>
    <AssemblyName>VanillaPacks</AssemblyName>
    <Version>0.1.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\PackmasterLib\PackmasterLib.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>
</Project>
